export const motorwayModelMap: Record<
  string,
  Record<string, string | string[]>
> = {
  "ASTON MARTIN": {
    DB11: "DB11",
    DB9: "DB9",
    "V8 Vantage": "V8 VANTAGE",
    "V12 Vantage": "V12 VANTAGE",
    Vanquish: "VANQUISH",
    Rapide: "RAPIDE",
    DBS: "DBS",
  },
  AUDI: {
    A1: "A1",
    A3: "A3",
    A4: "A4",
    A5: "A5",
    A6: "A6",
    A7: "A7",
    A8: "A8",
    "E-Tron": "E-TRON",
    Q2: "Q2",
    Q3: "Q3",
    Q4: "Q4",
    Q5: "Q5",
    Q7: "Q7",
    Q8: "Q8",
    R8: "R8",
    RS3: "RS3",
    RS4: "RS4",
    RS5: "RS5",
    RS6: "RS6",
    RS7: "RS7",
    TT: "TT",
    TTS: "TTS",
    TTRS: "TTRS",
  },
  BMW: {
    "1 Series": "1 SERIES",
    "2 Series": "2 SERIES",
    "3 Series": "3 SERIES",
    "4 Series": "4 SERIES",
    "5 Series": "5 SERIES",
    "6 Series": "6 SERIES",
    "7 Series": "7 SERIES",
    "8 Series": "8 SERIES",
    X1: "X1",
    X2: "X2",
    X3: "X3",
    X4: "X4",
    X5: "X5",
    X6: "X6",
    X7: "X7",
    Z4: "Z4",
    Z8: "Z8",
    Z1: "Z1",
    Z3: "Z3",
    Z5: "Z5",
    Z6: "Z6",
    Z7: "Z7",
    Z9: "Z9",
    i3: "I3",
    i4: "I4",
    iX: "IX",
    M2: "M2",
    M3: "M3",
    M4: "M4",
    M5: "M5",
    M8: "M8",
    X3M: "X3M",
    X4M: "X4M",
    X5M: "X5M",
    X6M: "X6M",
  },
  FORD: {
    "C-Max": "C-MAX",
    Connect: "CONNECT",
    Ecosport: "ECOSPORT",
    Edge: "EDGE",
    Fiesta: "FIESTA",
    Focus: "FOCUS",
    KA: "KA",
    Kuga: "KUGA",
    Mondeo: "MONDEO",
    Puma: "PUMA",
    "S-Max": "S-MAX",
    Galaxy: "GALAXY",
    Ranger: "RANGER",
    Transit: "TRANSIT",
    Mustang: "MUSTANG",
    Explorer: "EXPLORER",
  },
  HONDA: {
    Civic: "CIVIC",
    Jazz: "JAZZ",
    "CR-V": "CR-V",
    "HR-V": "HR-V",
    Accord: "ACCORD",
    Insight: "INSIGHT",
    "e:Ny1": "E:NY1",
    "CR-Z": "CR-Z",
  },
  HYUNDAI: {
    Coupe: "COUPE",
    Ioniq: "IONIQ",
    Kona: "KONA",
    i30: "I30",
    i40: "I40",
    Tucson: "TUCSON",
    "Santa Fe": "SANTA FE",
    Bayon: "BAYON",
    i10: "I10",
    i20: "I20",
  },
  JAGUAR: {
    "F-Pace": "F-PACE",
    "F-Type": "F-TYPE",
    XE: "XE",
    XF: "XF",
    XJ: "XJ",
    XK: "XK",
    "E-Pace": "E-PACE",
    "I-Pace": "I-PACE",
  },
  KIA: {
    Ceed: "CEED",
    Niro: "NIRO",
    Optima: "OPTIMA",
    Picanto: "PICANTO",
    Sportage: "SPORTAGE",
    Sorento: "SORENTO",
    Stonic: "STONIC",
    EV6: "EV6",
    Soul: "SOUL",
    Rio: "RIO",
  },
  "LAND ROVER": {
    Defender: "DEFENDER",
    Discovery: "DISCOVERY",
    Freelander: "FREELANDER",
    "Range Rover": "RANGE ROVER",
    "Range Rover Sport": "RANGE ROVER SPORT",
    "Range Rover Evoque": "RANGE ROVER EVOQUE",
    "Range Rover Velar": "RANGE ROVER VELAR",
    "Discovery Sport": "DISCOVERY SPORT",
  },
  LEXUS: {
    IS: ["IS200", "IS220", "IS250", "IS300", "ISF"],
    LS: ["LS400", "LS430", "LS460", "LS500", "LS600"],
    NX: ["NX200T", "NX300H", "NX350H", "NX450H"],
    RX: ["RX200", "RX300", "RX350", "RX400", "RX450", "RXL450"],
    SC: ["SC300", "SC400", "SC430"],
    UX: ["UX200", "UX250H", "UX300E"],
    ES: ["ES200", "ES250", "ES300H", "ES350"],
    GS: ["GS200T", "GS250", "GS300H", "GS350", "GS450H", "GS460", "GSF"],
    LC: ["LC500", "LC500H"],
    RC: ["RC200T", "RC300", "RC350", "RCF"],
    LBX: ["LBX200", "LBX250H"],
  },
  MAZDA: {
    "6": "6",
    "MX-30": "MX-30",
    "MX-5": "MX-5",
    "3": "3",
    "2": "2",
    "CX-3": "CX-3",
    "CX-30": "CX-30",
    "CX-5": "CX-5",
    "CX-60": "CX-60",
    "CX-80": "CX-80",
  },
  "MERCEDES-BENZ": {
    "A-Class": "A-CLASS",
    "B-Class": "B-CLASS",
    "C-Class": "C-CLASS",
    "CLA-Class": "CLA-CLASS",
    "CLE-Class": "CLE-CLASS",
    "CLK-Class": "CLK-CLASS",
    "CLS-Class": "CLS-CLASS",
    "E-Class": "E-CLASS",
    "EQA-Class": "EQA-CLASS",
    "EQB-Class": "EQB-CLASS",
    "EQC-Class": "EQC-CLASS",
    "EQE-Class": "EQE-CLASS",
    "EQS-Class": "EQS-CLASS",
    "EQV-Class": "EQV-CLASS",
    "G-Class": "G-CLASS",
    "GL-Class": "GL-CLASS",
    "GLA-Class": "GLA-CLASS",
    "GLB-Class": "GLB-CLASS",
    "GLC-Class": "GLC-CLASS",
    "GLE-Class": "GLE-CLASS",
    "GLS-Class": "GLS-CLASS",
    "M-Class": "M-CLASS",
    "S-Class": "S-CLASS",
    "SL-Class": "SL-CLASS",
    "SLC-Class": "SLC-CLASS",
    "SLK-Class": "SLK-CLASS",
    "V-Class": "V-CLASS",
    "AMG A": "AMG A",
    "AMG C": "AMG C",
    "AMG E": "AMG E",
    "AMG GLC": "AMG GLC",
    "AMG GLE": "AMG GLE",
    "AMG GLS": "AMG GLS",
    "AMG SL": "AMG SL",
    "AMG SLK": "AMG SLK",
  },
  NISSAN: {
    Micra: "MICRA",
    Qashqai: "QASHQAI",
    Juke: "JUKE",
    Leaf: "LEAF",
    Ariya: "ARIYA",
    Note: "NOTE",
    Pulsar: "PULSAR",
    Almera: "ALMERA",
    Sentra: "SENTRA",
    Altima: "ALTIMA",
  },
  PEUGEOT: {
    "108": "108",
    "2008": "2008",
    "206": "206",
    "207": "207",
    "208": "208",
    "3008": "3008",
    "307": "307",
    "308": "308",
    "407": "407",
    "5008": "5008",
    "508": "508",
    Rifter: "RIFTER",
    Traveller: "TRAVELLER",
  },
  PORSCHE: {
    "911": "911",
    Boxster: "BOXSTER",
    Cayman: "CAYMAN",
    Macan: "MACAN",
    Panamera: "PANAMERA",
    Taycan: "TAYCAN",
    Cayenne: "CAYENNE",
    Carrera: "CARRERA",
    GT3: "GT3",
    GT4: "GT4",
  },
  RENAULT: {
    Espace: "ESPACE",
    Megane: "MEGANE",
    Modus: "MODUS",
    Scenic: "SCENIC",
    Zoe: "ZOE",
    Clio: "CLIO",
    Captur: "CAPTUR",
    Kadjar: "KADJAR",
    Austral: "AUSTRAL",
    Arkana: "ARKANA",
  },
  SEAT: {
    Ibiza: "IBIZA",
    Leon: "LEON",
    Mii: "MII",
    Arona: "ARONA",
    Ateca: "ATECA",
    Tarraco: "TARRACO",
    Alhambra: "ALHAMBRA",
    Toledo: "TOLEDO",
  },
  SKODA: {
    Citigo: "CITIGO",
    Fabia: "FABIA",
    Karoq: "KAROQ",
    Kodiaq: "KODIAQ",
    Octavia: "OCTAVIA",
    Rapid: "RAPID",
    Roomster: "ROOMSTER",
    Superb: "SUPERB",
    Scala: "SCALA",
    Kamiq: "KAMIQ",
    Enyaq: "ENYAQ",
  },
  TESLA: {
    "Model 3": "MODEL 3",
    "Model S": "MODEL S",
    "Model X": "MODEL X",
    "Model Y": "MODEL Y",
    Roadster: "ROADSTER",
    Cybertruck: "CYBERTRUCK",
  },
  TOYOTA: {
    Auris: "AURIS",
    Avensis: "AVENSIS",
    Aygo: "AYGO",
    Corolla: "COROLLA",
    LandCruiser: "LAND CRUISER",
    Prius: "PRIUS",
    "Proace City": "PROACE CITY",
    Proace: "PROACE",
    Yaris: "YARIS",
    "C-HR": "C-HR",
    RAV4: "RAV4",
    Highlander: "HIGHLANDER",
    Camry: "CAMRY",
    Supra: "SUPRA",
    bZ4X: "BZ4X",
  },
  VAUXHALL: {
    Adam: "ADAM",
    Astra: "ASTRA",
    Combo: "COMBO",
    Corsa: "CORSA",
    Crossland: "CROSSLAND",
    Grandland: "GRANDLAND",
    Insignia: "INSIGNIA",
    Mokka: "MOKKA",
    Viva: "VIVA",
    Vivaro: "VIVARO",
    Zafira: "ZAFIRA",
    "Combo Life": "COMBO LIFE",
    "Mokka-e": "MOKKA-E",
    "Corsa-e": "CORSA-E",
  },
  VOLKSWAGEN: {
    Arteon: "ARTEON",
    Caddy: "CADDY",
    California: "CALIFORNIA",
    Caravelle: "CARAVELLE",
    Golf: "GOLF",
    "ID.7": "ID.7",
    Passat: "PASSAT",
    Polo: "POLO",
    "T-Roc": "T-ROC",
    Tiguan: "TIGUAN",
    "UP!": "UP!",
    "ID.3": "ID.3",
    "ID.4": "ID.4",
    "ID.5": "ID.5",
    Touran: "TOURAN",
    Sharan: "SHARAN",
    Touareg: "TOUAREG",
    "T-Cross": "T-CROSS",
    Taigo: "TAIGO",
  },
  VOLVO: {
    S60: "S60",
    S90: "S90",
    V40: "V40",
    V60: "V60",
    V70: "V70",
    V90: "V90",
    XC40: "XC40",
    XC60: "XC60",
    XC90: "XC90",
    C40: "C40",
    EX30: "EX30",
    EX90: "EX90",
  },
};

// Helper function to get the Motorway model name(s)
export function getMotorwayModelName(
  make: string,
  model: string
): string | string[] {
  const makeUpper = make.toUpperCase();
  const modelUpper = model.toUpperCase();

  // Check if we have a mapping for this make
  if (motorwayModelMap[makeUpper]) {
    // Check if we have a mapping for this model
    if (motorwayModelMap[makeUpper][modelUpper]) {
      return motorwayModelMap[makeUpper][modelUpper];
    }

    // If no exact match, try to find a partial match
    for (const [key, value] of Object.entries(motorwayModelMap[makeUpper])) {
      if (
        key.toUpperCase().includes(modelUpper) ||
        modelUpper.includes(key.toUpperCase())
      ) {
        return value;
      }
    }
  }

  // If no mapping found, return the original model in uppercase (Motorway's default format)
  return modelUpper;
}
