export const modelGroupMap: Record<string, Record<string, string>> = {
  AUDI: {
    A1: "A1 Line",
    A3: "A3 Line",
    A4: "A4 Line",
    A5: "A5 Line",
    A6: "A6 Line",
    A7: "A7 Line",
    A8: "A8 Line",
    "E-Tron": "E-Tron Line",
    Q2: "Q2 Line",
    Q3: "Q3 Line",
    Q4: "Q4 Line",
    Q5: "Q5 Line",
    Q7: "Q7 Line",
    Q8: "Q8 Line",
    R8: "R8 Line",
    RS: "RS Line",
    TT: "TT Line",
  },
  BMW: {
    "1 Series": "1 Series",
    "2 Series": "2 Series,2 Series Active/Grand  Tourer",
    "3 Series": "3 Series",
    "4 Series": "4 Series",
    "5 Series": "5 Series",
    "6 Series": "6 Series",
    "7 Series": "7 Series",
    "8 Series": "8 Series",
    Alpina: "Alpina Series",
    "M Series": "M Series",
    X1: "X1 Series",
    X2: "X2 Series",
    X3: "X3 Series",
    X4: "X4 Series",
    X5: "X5 Series",
    X6: "X6 Series",
    X7: "X7 Series",
    Z4: "Z4 Series",
    i3: "i3 Series",
    i4: "i4 Series",
    iX: "iX Series",
  },
  CITROEN: {
    Berlingo: "Berlingo CAR Range",
    C1: "C1 Range",
    C3: "C3 Range",
    "C4 Picasso": "C4 Picasso Range",
    C4: "C4 Range",
    "C4 SpaceTourer": "C4 SpaceTourer Range",
    C5: "C5 Range",
    "DS3 / DS3c": "DS3 / DS3c Range",
    SpaceTourer: "SpaceTourer Range",
  },
  FIAT: {
    "500": "500 Range",
    "500L": "500L Range",
    "500X": "500X Range",
    Panda: "Panda Range",
    Punto: "Punto Range",
    Tipo: "Tipo Range",
  },
  FORD: {
    "C-Max": "C-Max Range",
    "Connect CAR": "Connect CAR Range",
    Ecosport: "Ecosport Range",
    Edge: "Edge Range",
    Fiesta: "Fiesta Range",
    Focus: "Focus Range",
    KA: "KA Range",
    Kuga: "Kuga Range",
    Mondeo: "Mondeo Range",
    Puma: "Puma Range",
    "S-Max": "S-Max Range",
  },
  HONDA: {
    Civic: "Civic Range",
    Jazz: "Jazz Range",
  },
  HYUNDAI: {
    Coupe: "Coupe Range",
    Ioniq: "Ioniq Range",
    Kona: "Kona Range",
    i30: "i30 Range",
    i40: "i40 Range",
  },
  JAGUAR: {
    "F-Pace": "F-Pace Series",
    "F-Type": "F-Type Series",
    XE: "XE Series",
    XF: "XF Series",
    XJ: "XJ Series",
    XK: "XK Series",
  },
  KIA: {
    Ceed: "CEED Range",
    Niro: "Niro Range",
    Optima: "Optima Range",
    Picanto: "Picanto Range",
  },
  "LAND ROVER": {
    Defender: "Defender Series (2020)",
    Discovery: "Discovery Series",
    Freelander: "Freelander Series",
    "Range Rover": "Range Rover Series",
  },
  LEXUS: {
    IS: "IS Series",
    LS: "LS Series",
    NX: "NX Series",
    RX: "RX Series",
    SC: "SC Series",
    UX: "UX Series",
  },
  MASERATI: {},
  MAZDA: {
    "6 Range": "6 Range",
    "MX-30 Range": "MX-30 Range",
    "MX-5 Range": "MX-5 Range",
  },
  MCLAREN: {
    "Sport Series": "Sport Series",
  },
  "MERCEDES-BENZ": {
    "A Class": "A - Class",
    "AMG A": "AMG Series - A",
    "AMG C": "AMG Series - C",
    "AMG E": "AMG Series - E",
    "AMG EQE": "AMG Series - EQE",
    "AMG GLC": "AMG Series - GLC",
    "AMG GLE": "AMG Series - GLE",
    "AMG GLS": "AMG Series - GLS",
    "AMG SL": "AMG Series - SL",
    "AMG SLK": "AMG Series - SLK",
    "B Class": "B - Class",
    "C Class": "C - Class",
    "CLA Class": "CLA - Class",
    "CLE Class": "CLE - Class",
    "CLK Class": "CLK - Class",
    "CLS Class": "CLS - Class",
    "E Class": "E - Class",
    "EQA Class": "EQA - Class",
    "EQB Class": "EQB - Class",
    "EQC Class": "EQC - Class",
    "EQE Class": "EQE - Class",
    "EQS Class": "EQS - Class",
    "EQV Class": "EQV - Class",
    "G Class": "G - Class",
    "GL Class": "GL - Class",
    "GLA Class": "GLA - Class",
    "GLB Class": "GLB - Class",
    "GLC Class": "GLC - Class",
    "GLE Class": "GLE - Class",
    "GLS Class": "GLS - Class",
    "M Class": "M - Class",
    Maybach: "Maybach Series",
    "S Class": "S - Class",
    "SL Class": "SL - Class",
    "SLC Class": "SLC - Class",
    "SLK Class": "SLK - Class",
    "V Class": "V - Class",
  },
  MITSUBISHI: {
    Outlander: "Outlander Range",
  },
  NISSAN: {
    Micra: "Micra Range",
    "NV200 CAR": "NV200 CAR Range",
    Qashqai: "Qashqai Range",
  },
  PEUGEOT: {
    "108": "108 Range",
    "2008": "2008 Range",
    "206": "206 Range",
    "207": "207 Range",
    "208": "208 Range",
    "3008": "3008 Range",
    "307": "307 Range",
    "308": "308 Range",
    "407": "407 Range",
    "5008": "5008 Range",
    "508": "508 Range",
    Rifter: "Rifter Range",
    Traveller: "Traveller Range",
  },
  PORSCHE: {
    "911": "911 Range",
    Boxster: "Boxster Range",
    Cayman: "Cayman Range",
    Macan: "Macan Range",
    Panamera: "Panamera Range",
    Taycan: "Taycan Range",
  },
  RENAULT: {
    Espace: "Espace Range",
    Megane: "Megane Range",
    Modus: "Modus Range",
    Scenic: "Scenic Range",
    Zoe: "Zoe Range",
  },
  ROVER: {
    "600 Range": "600 Range",
  },
  SAAB: {
    "9-5 Range": "9-5 Range",
  },
  SEAT: {
    Ibiza: "Ibiza Range",
    Leon: "Leon Range",
    Mii: "Mii Range",
  },
  SKODA: {
    Citigo: "Citigo Range",
    Fabia: "Fabia Range",
    Karoq: "Karoq Range",
    Kodiaq: "Kodiaq Range",
    Octavia: "Octavia Range",
    Rapid: "Rapid Range",
    Roomster: "Roomster Range",
    Superb: "Superb Range",
    "Yeti Range": "Yeti Range",
  },
  SMART: {
    ForFour: "ForFour Range",
    ForTwo: "ForTwo Range",
  },
  SSANGYONG: {
    Korando: "Korando Range",
    Tivoli: "Tivoli Range",
  },
  SUBARU: {
    Impreza: "Impreza Range",
  },
  SUZUKI: {
    Jimny: "Jimny Range",
    Vitara: "Vitara Range",
  },
  TESLA: {},
  TOYOTA: {
    Auris: "Auris Range",
    Avensis: "Avensis Range",
    Aygo: "Aygo Range",
    Corolla: "Corolla Range",
    LandCruiser: "LandCruiser Range",
    Prius: "Prius Range",
    Proace: "Proace Range",
    Yaris: "Yaris Range",
  },
  VAUXHALL: {
    Adam: "Adam Range",
    Astra: "Astra Range",
    Combo: "Combo Range",
    Corsa: "Corsa Range",
    Crossland: "Crossland Range",
    Grandland: "Grandland Range",
    Insignia: "Insignia Range",
    Mokka: "Mokka Range",
    Viva: "Viva Range",
    Vivaro: "Vivaro Range",
    Zafira: "Zafira Range",
  },
  VOLKSWAGEN: {
    Arteon: "Arteon Range",
    "Caddy CAR": "Caddy CAR Range",
    California: "California Range",
    Caravelle: "Caravelle Range",
    Golf: "Golf Range",
    "ID.7": "ID.7 Range",
    Passat: "Passat Range",
    Polo: "Polo Range",
    "T-Roc": "T-Roc Range",
    Tiguan: "Tiguan Range",
    "UP!": "UP! Range",
  },
  VOLVO: {
    S60: "S60 Range",
    S90: "S90 Range",
    V40: "V40 Range",
    V60: "V60 Range",
    V70: "V70 Range",
    V90: "V90 Range",
    XC40: "XC40 Range",
    XC60: "XC60 Range",
    XC90: "XC90 Range",
  },
};
